[workspace]
name = "voxcpm-local"
channels = ["conda-forge"]
platforms = ["win-64"]
requires-pixi = ">=0.61.0"

[system-requirements]
cuda = "12.8"

[dependencies]
python = "3.12.*"
pip = "*"
ffmpeg = "*"

[pypi-dependencies]
voxcpm = { path = "./VoxCPM", editable = true }
fastapi = ">=0.115,<1"
uvicorn = { version = ">=0.32,<1", extras = ["standard"] }
python-multipart = ">=0.0.20,<1"

[target.win-64.pypi-dependencies]
torch = { url = "https://mirrors.aliyun.com/pytorch-wheels/cu128/torch-2.7.0%2Bcu128-cp312-cp312-win_amd64.whl" }
torchaudio = { url = "https://mirrors.aliyun.com/pytorch-wheels/cu128/torchaudio-2.7.0%2Bcu128-cp312-cp312-win_amd64.whl" }
torchvision = { url = "https://mirrors.aliyun.com/pytorch-wheels/cu128/torchvision-0.22.0%2Bcu128-cp312-cp312-win_amd64.whl" }

[tasks]
install = { cmd = "python scripts/download_modelscope_model.py --model-id OpenBMB/VoxCPM2" }
install-asr = { cmd = "python scripts/download_modelscope_model.py --model-id iic/SenseVoiceSmall" }
adopt-asr-cache = { cmd = "python scripts/adopt_modelscope_cache.py --model-id iic/SenseVoiceSmall" }
webui = { cmd = "python scripts/launch_voxcpm.py --mode webui --model-id models/OpenBMB__VoxCPM2 --port 7860" }
webui-asr = { cmd = "python scripts/launch_voxcpm.py --mode webui --model-id models/OpenBMB__VoxCPM2 --port 7860 --enable-asr --asr-model-id models/iic__SenseVoiceSmall" }
api = { cmd = "python scripts/launch_voxcpm.py --mode api --model-id models/OpenBMB__VoxCPM2 --port 8000 --preload-model"  }
api-asr = { cmd = "python scripts/launch_voxcpm.py --mode api --model-id models/OpenBMB__VoxCPM2 --port 8000 --preload-model --enable-asr --asr-model-id models/iic__SenseVoiceSmall"  }
combined = { cmd = "python scripts/launch_voxcpm.py --mode combined --model-id models/OpenBMB__VoxCPM2 --port 7860" }
combined-asr = { cmd = "python scripts/launch_voxcpm.py --mode combined --model-id models/OpenBMB__VoxCPM2 --port 7860 --enable-asr --asr-model-id models/iic__SenseVoiceSmall" }
launcher-help = { cmd = "python scripts/launch_voxcpm.py --help" }
